In [85]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score,accuracy_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif

df=pd.read_csv("C:/Users/jyoth/Downloads/eegdatset.csv")
df

FP1_power_delta  FP1_power_theta  FP1_power_alpha  FP1_power_beta  \
0           15.980332         8.633358         3.092433        0.846559   
1          223.267803        41.573241        13.043525        6.463381   
2          158.673907        31.788608         9.956198        3.736977   
3           29.767326         3.875543         1.553127        0.438266   
4           33.821075         3.635210         1.347280        0.313205   
...               ...              ...              ...             ...   
2211        93.573012         9.060520         4.980545        4.839014   
2212        15.523587         3.195279         1.268068        0.788076   
2213        17.580684         2.208482         0.512273        0.122671   
2214        35.847315         3.354388         2.280252        2.368355   
2215        26.299626         2.783714         1.020452        0.693122   

      FP1_power_gamma  FP2_power_delta  FP2_power_theta  FP2_power_alpha  \
0            0.372832        17.581626         9.937238         3.485713   
1            6.168712       298.274432        50.013025        14.411482   
2            2.926979       232.762742        39.332981        10.956081   
3            0.140495        45.206547         5.173542         2.028637   
4            0.080396        55.670043         4.925017         1.783729   
...               ...              ...              ...              ...   
2211         2.402408       103.479883        10.121498         5.411378   
2212         0.350012        15.177286         3.420879         1.324339   
2213         0.042173        18.294247         2.380609         0.560150   
2214         1.217081        33.889844         3.048972         1.356364   
2215         0.328914        26.055785         2.918337         0.944078   

      FP2_power_beta  FP2_power_gamma  ...  T5_STD_D4  T5_STD_D5  T5_STD_D6  \
0           0.945396         0.428797  ...  31.427918  29.699413  32.013546   
1           6.659230         4.942250  ...  24.822720  47.185918  93.619195   
2           3.478036         2.153082  ...  21.708222  47.412375  85.729645   
3           0.528962         0.161283  ...  26.319506  39.628894  51.473202   
4           0.394463         0.102254  ...  26.111048  39.177537  52.925676   
...              ...              ...  ...        ...        ...        ...   
2211        5.112091         2.410508  ...  28.420439  35.838353  55.575530   
2212        0.772379         0.340149  ...  25.567858  29.982968  19.842641   
2213        0.132999         0.045041  ...  15.186601  23.281200  31.479138   
2214        1.159790         0.632721  ...  20.376012  23.182715  24.117538   
2215        0.491128         0.199761  ...  21.973431  24.301343  21.518677   

      T6_STD_D1  T6_STD_D2  T6_STD_D3  T6_STD_D4   T6_STD_D5   T6_STD_D6  \
0      3.583559  12.529528  45.831132  61.890813   34.783454   33.245906   
1     14.158489  15.217886  30.927407  77.324322  153.442359  213.780950   
2      9.493639  11.824569  24.555772  59.229187  112.406306  171.618208   
3      1.872515   5.392639  17.296780  35.824586   44.892899   79.613460   
4      1.408291   4.556997  12.733549  25.676801   44.406617   94.770581   
...         ...        ...        ...        ...         ...         ...   
2211  13.980452  15.455901  17.599760  35.736742   44.639277   52.441626   
2212   3.896454   4.507998   9.674004  29.642064   32.178907   23.513508   
2213   1.183803   2.253192   6.133507  18.810084   29.451244   40.868567   
2214   6.995231   6.819144   9.820588  26.620415   30.167641   31.778504   
2215   2.351333   3.269492   7.700107  25.207972   28.056602   37.080093   

      epileptic_  
0              1  
1              1  
2              1  
3              1  
4              1  
...          ...  
2211           0  
2212           0  
2213           0  
2214           0  
2215           0  

[2216 rows x 668 columns]

In [86]:
df['epileptic_'].value_counts()

0    1196
1    1020
Name: epileptic_, dtype: int64

In [87]:
df.columns

Index(['FP1_power_delta', 'FP1_power_theta', 'FP1_power_alpha',
       'FP1_power_beta', 'FP1_power_gamma', 'FP2_power_delta',
       'FP2_power_theta', 'FP2_power_alpha', 'FP2_power_beta',
       'FP2_power_gamma',
       ...
       'T5_STD_D4', 'T5_STD_D5', 'T5_STD_D6', 'T6_STD_D1', 'T6_STD_D2',
       'T6_STD_D3', 'T6_STD_D4', 'T6_STD_D5', 'T6_STD_D6', 'epileptic_'],
      dtype='object', length=668)

In [88]:
df.shape

(2216, 668)

In [89]:
df.isnull().sum()

FP1_power_delta    0
FP1_power_theta    0
FP1_power_alpha    0
FP1_power_beta     0
FP1_power_gamma    0
                  ..
T6_STD_D3          0
T6_STD_D4          0
T6_STD_D5          0
T6_STD_D6          0
epileptic_         0
Length: 668, dtype: int64

In [90]:
df.isnull().sum().sum()

0

In [91]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [92]:
X.shape

(2216, 667)

In [93]:
y.shape

(2216,)

In [94]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=0)

In [95]:
X_train.shape

(1551, 667)

In [96]:
y_train.shape

(1551,)

In [97]:
X_test.shape

(665, 667)

In [98]:
y_test.shape

(665,)

# STANDARDIZING

In [99]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
X_train2=st.fit_transform(X_train)
X_test2=st.transform(X_test)

# KNN 

In [100]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=100)

KNN_fit = model.fit(X_train,y_train)
y_pred = KNN_fit.predict(X_test)

acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

In [101]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=[0,1]))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[269  87]
 [103 206]]
Accuracy : 71.43%
Precision : 70.31%
Recall : 66.67%
f1_score : 68.44%


In [102]:
KNN_fit2 = model.fit(X_train2,y_train)
y_pred2 = KNN_fit2.predict(X_test2)

In [103]:
acc_score=accuracy_score(y_test,y_pred2)
pre_score = precision_score(y_test,y_pred2)
recall = recall_score(y_test,y_pred2)
f1 = f1_score(y_test,y_pred2)

In [104]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred2, labels=[0,1]))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[248 108]
 [124 185]]
Accuracy : 65.11%
Precision : 63.14%
Recall : 59.87%
f1_score : 61.46%


# DECISION TREE

In [105]:
from sklearn.tree import DecisionTreeClassifier
model1 = DecisionTreeClassifier(criterion = 'entropy')

dt_fit = model1.fit(X_train,y_train)
y_pred = dt_fit.predict(X_test)

acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

In [106]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=[0,1]))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[274  82]
 [ 80 229]]
Accuracy : 75.64%
Precision : 73.63%
Recall : 74.11%
f1_score : 73.87%


In [107]:
dt_fit2 = model1.fit(X_train2,y_train)
y_pred2 = dt_fit2.predict(X_test2)

In [108]:
acc_score=accuracy_score(y_test,y_pred2)
pre_score = precision_score(y_test,y_pred2)
recall = recall_score(y_test,y_pred2)
f1 = f1_score(y_test,y_pred2)

In [109]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred2, labels=[0,1]))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[271  85]
 [ 70 239]]
Accuracy : 76.69%
Precision : 73.77%
Recall : 77.35%
f1_score : 75.51%


# LOGISTIC REGRESSION

In [110]:
from sklearn.linear_model import LogisticRegression
model2 = LogisticRegression()
import warnings
warnings.filterwarnings("ignore")

lr_fit = model2.fit(X_train,y_train)
y_pred = lr_fit.predict(X_test)

acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

In [111]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=[0,1]))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[131 225]
 [ 23 286]]
Accuracy : 62.71%
Precision : 55.97%
Recall : 92.56%
f1_score : 69.76%


In [112]:
lr_fit2 = model2.fit(X_train2,y_train)
y_pred2 = lr_fit2.predict(X_test2)

In [113]:
acc_score=accuracy_score(y_test,y_pred2)
pre_score = precision_score(y_test,y_pred2)
recall = recall_score(y_test,y_pred2)
f1 = f1_score(y_test,y_pred2)

In [114]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=[0,1]))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[131 225]
 [ 23 286]]
Accuracy : 78.05%
Precision : 76.9%
Recall : 75.4%
f1_score : 76.14%


# SVM

In [115]:
from sklearn import svm
model4 = svm.SVC()

sv_fit = model4.fit(X_train,y_train)
y_pred = sv_fit.predict(X_test)

acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

In [116]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=[0,1]))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[346  10]
 [292  17]]
Accuracy : 54.59%
Precision : 62.96%
Recall : 5.5%
f1_score : 10.12%


In [117]:
from sklearn.svm import SVC
model5=SVC(kernel='linear')

sv_fitt = model5.fit(X_train,y_train)
y_pred = sv_fitt.predict(X_test)

acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

In [118]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=[0,1]))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[248 108]
 [ 70 239]]
Accuracy : 73.23%
Precision : 68.88%
Recall : 77.35%
f1_score : 72.87%


In [119]:
sv_fitt2 = model5.fit(X_train2,y_train)
y_pred2 = sv_fitt2.predict(X_test2)

In [120]:
acc_score=accuracy_score(y_test,y_pred2)
pre_score = precision_score(y_test,y_pred2)
recall = recall_score(y_test,y_pred2)
f1 = f1_score(y_test,y_pred2)

In [121]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred2, labels=[0,1]))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[279  77]
 [ 77 232]]
Accuracy : 76.84%
Precision : 75.08%
Recall : 75.08%
f1_score : 75.08%


# RANDOM FOREST

In [72]:
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier(n_estimators=400)

rf_fit = model3.fit(X_train,y_train)
y_pred = rf_fit.predict(X_test)

acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

In [50]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred2, labels=[0,1]))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[286  70]
 [ 76 233]]
Accuracy : 78.05%
Precision : 76.9%
Recall : 75.4%
f1_score : 76.14%


In [74]:
rf_fit2 = model3.fit(X_train2,y_train)
y_pred2 = rf_fit2.predict(X_test2)

In [75]:
acc_score=accuracy_score(y_test,y_pred2)
pre_score = precision_score(y_test,y_pred2)
recall = recall_score(y_test,y_pred2)
f1 = f1_score(y_test,y_pred2)

In [76]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred2, labels=[0,1]))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[306  50]
 [ 56 253]]
Accuracy : 84.06%
Precision : 83.5%
Recall : 81.88%
f1_score : 82.68%


In [63]:
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, AdaBoostClassifier ,VotingClassifier
from sklearn.metrics import accuracy_score

In [66]:
gb_classifier = GradientBoostingClassifier(n_estimators=400)
gb_classifier.fit(X_train, y_train)
gb_predictions = gb_classifier.predict(X_test)
gb_accuracy = accuracy_score(y_test, gb_predictions)
print("Gradient Boosting Accuracy:", gb_accuracy)

Gradient Boosting Accuracy: 0.8466165413533835


In [80]:
for i in range(1,11):
    base = DecisionTreeClassifier(max_depth=i)

    ab_classifier = AdaBoostClassifier(base_estimator=base)
    ab_classifier.fit(X_train, y_train)
    ab_predictions = ab_classifier.predict(X_test)
    ab_accuracy = accuracy_score(y_test, ab_predictions)
    print("AdaBoost Accuracy:", ab_accuracy)

AdaBoost Accuracy: 0.8210526315789474
AdaBoost Accuracy: 0.8285714285714286
AdaBoost Accuracy: 0.7879699248120301
AdaBoost Accuracy: 0.7864661654135339
AdaBoost Accuracy: 0.793984962406015
AdaBoost Accuracy: 0.7819548872180451
AdaBoost Accuracy: 0.8
AdaBoost Accuracy: 0.7954887218045112
AdaBoost Accuracy: 0.8045112781954887
AdaBoost Accuracy: 0.793984962406015


In [83]:
n_trees = [10, 50, 100, 500, 1000]
for n in n_trees:
    ab_classifier = AdaBoostClassifier(n_estimators=n)
    ab_classifier.fit(X_train, y_train)
    ab_predictions = ab_classifier.predict(X_test)
    ab_accuracy = accuracy_score(y_test, ab_predictions)
    print("AdaBoost Accuracy:", ab_accuracy)

AdaBoost Accuracy: 0.750375939849624
AdaBoost Accuracy: 0.8210526315789474
AdaBoost Accuracy: 0.8210526315789474
AdaBoost Accuracy: 0.8300751879699249
AdaBoost Accuracy: 0.8285714285714286
